### ISSUE TITLE
컴포넌트 개발 : Typography

### ISSUE THREAD

**Issue by Kyun2da** [woowa-techcamp-2021/deal-2#52]
![스크린샷 2021-07-12 오후 6 11 55](https://user-images.githubusercontent.com/50328132/125261891-a7576e80-e33c-11eb-8d68-c52cbfbdd8b7.png)

**Comment by CurlyBat** [comment]
이거는 닫아도 되지않을까요?

**Comment by Kyun2da** [comment]
> 이거는 닫아도 되지않을까요?

네 닫아도 될 것 같아요! 제가 닫을게요 :)
